---
- name: Copy HTTPS configuration
  copy:
    src: "{{ https_conf_file }}"
    dest: "{{ nginx_conf_dir }}/default.conf"
    remote_src: yes

- name: Load HTTPS conf
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}"

