---
- name: Load HTTP conf
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}"

- name: Wait for SSL certificate to be generated
  wait_for:
    path: "{{ app_dir }}/letsencrypt/live/{{ domain }}/fullchain.pem"
    state: present
    timeout: 300

- name: Ensure the SSL certificate was generated successfully
  stat:
    path: "{{ app_dir }}/letsencrypt/live/{{ domain }}/fullchain.pem"
  register: cert_stat

- name: Stop all services
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}"
    state: stopped
  register: output

# - name: Check if SSL certificate was generated in the container
#   community.docker.docker_container_exec:
#     container: "{{ nginx_container_name }}"
#     command: "ls /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
#   register: cert_check_result
#   ignore_errors: yes
#   retries: 10
#   delay: 30
#   until: cert_check_result.rc == 0

- name: Copy HTTPS configuration
  copy:
    src: "{{ https_conf_file }}"
    dest: "{{ nginx_conf_dir }}/default.conf"
    remote_src: yes

- name: Load HTTPS conf
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}"

