---
- name: Install docker
  apt:
    name: docker
    update_cache: yes
    cache_valid_time: 3600

- name: Install docker-compose
  apt:
    name: docker-compose-plugin
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure Docker service is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes