---
- name: Ensure the destination directory exists
  ansible.builtin.file:
    path: "{{ app_dir }}/letsencrypt"
    state: directory
    mode: '0755'

- name: Copy existing SSL Certificate
  ansible.builtin.copy:
    src: ./files/{{ domain }}
    dest: {{ app_dir }}/letsencrypt
    mode: '0644'